package fr.sigl.intg.model;
// Generated Jan 3, 2016 2:05:43 PM by Hibernate Tools 3.4.0.CR1

/**
 * Image generated by hbm2java
 */
public class Image implements java.io.Serializable {

	private int imgId;
	private Tag tag;
	private byte[] imgBytes;

	public Image() {
	}

	public Image(int imgId, Tag tag, byte[] imgBytes) {
		this.imgId = imgId;
		this.tag = tag;
		this.imgBytes = imgBytes;
	}

	public int getImgId() {
		return this.imgId;
	}

	public void setImgId(int imgId) {
		this.imgId = imgId;
	}

	public Tag getTag() {
		return this.tag;
	}

	public void setTag(Tag tag) {
		this.tag = tag;
	}

	public byte[] getImgBytes() {
		return this.imgBytes;
	}

	public void setImgBytes(byte[] imgBytes) {
		this.imgBytes = imgBytes;
	}

}
