package fr.sigl.intg.model;
// Generated Jan 3, 2016 2:05:43 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Tag generated by hbm2java
 */
public class Tag implements java.io.Serializable {

	private int tagId;
	private Userlogin userlogin;
	private String tagName;
	private Date tagRegistrationdate;
	private String tagSupport;
	private String tagSupportspecificity;
	private String tagPlace;
	private String tagSize;
	private String tagAuthorfirstname;
	private String tagAuthorlastname;
	private Boolean tagIdverified;
	private String tagUsedtechnique;
	private String tagTrashleft;
	private String tagComment;
	private Set images = new HashSet(0);

	public Tag() {
	}

	public Tag(int tagId, Userlogin userlogin, String tagName, Date tagRegistrationdate, String tagSupport,
			String tagPlace) {
		this.tagId = tagId;
		this.userlogin = userlogin;
		this.tagName = tagName;
		this.tagRegistrationdate = tagRegistrationdate;
		this.tagSupport = tagSupport;
		this.tagPlace = tagPlace;
	}

	public Tag(int tagId, Userlogin userlogin, String tagName, Date tagRegistrationdate, String tagSupport,
			String tagSupportspecificity, String tagPlace, String tagSize, String tagAuthorfirstname,
			String tagAuthorlastname, Boolean tagIdverified, String tagUsedtechnique, String tagTrashleft,
			String tagComment, Set images) {
		this.tagId = tagId;
		this.userlogin = userlogin;
		this.tagName = tagName;
		this.tagRegistrationdate = tagRegistrationdate;
		this.tagSupport = tagSupport;
		this.tagSupportspecificity = tagSupportspecificity;
		this.tagPlace = tagPlace;
		this.tagSize = tagSize;
		this.tagAuthorfirstname = tagAuthorfirstname;
		this.tagAuthorlastname = tagAuthorlastname;
		this.tagIdverified = tagIdverified;
		this.tagUsedtechnique = tagUsedtechnique;
		this.tagTrashleft = tagTrashleft;
		this.tagComment = tagComment;
		this.images = images;
	}

	public int getTagId() {
		return this.tagId;
	}

	public void setTagId(int tagId) {
		this.tagId = tagId;
	}

	public Userlogin getUserlogin() {
		return this.userlogin;
	}

	public void setUserlogin(Userlogin userlogin) {
		this.userlogin = userlogin;
	}

	public String getTagName() {
		return this.tagName;
	}

	public void setTagName(String tagName) {
		this.tagName = tagName;
	}

	public Date getTagRegistrationdate() {
		return this.tagRegistrationdate;
	}

	public void setTagRegistrationdate(Date tagRegistrationdate) {
		this.tagRegistrationdate = tagRegistrationdate;
	}

	public String getTagSupport() {
		return this.tagSupport;
	}

	public void setTagSupport(String tagSupport) {
		this.tagSupport = tagSupport;
	}

	public String getTagSupportspecificity() {
		return this.tagSupportspecificity;
	}

	public void setTagSupportspecificity(String tagSupportspecificity) {
		this.tagSupportspecificity = tagSupportspecificity;
	}

	public String getTagPlace() {
		return this.tagPlace;
	}

	public void setTagPlace(String tagPlace) {
		this.tagPlace = tagPlace;
	}

	public String getTagSize() {
		return this.tagSize;
	}

	public void setTagSize(String tagSize) {
		this.tagSize = tagSize;
	}

	public String getTagAuthorfirstname() {
		return this.tagAuthorfirstname;
	}

	public void setTagAuthorfirstname(String tagAuthorfirstname) {
		this.tagAuthorfirstname = tagAuthorfirstname;
	}

	public String getTagAuthorlastname() {
		return this.tagAuthorlastname;
	}

	public void setTagAuthorlastname(String tagAuthorlastname) {
		this.tagAuthorlastname = tagAuthorlastname;
	}

	public Boolean getTagIdverified() {
		return this.tagIdverified;
	}

	public void setTagIdverified(Boolean tagIdverified) {
		this.tagIdverified = tagIdverified;
	}

	public String getTagUsedtechnique() {
		return this.tagUsedtechnique;
	}

	public void setTagUsedtechnique(String tagUsedtechnique) {
		this.tagUsedtechnique = tagUsedtechnique;
	}

	public String getTagTrashleft() {
		return this.tagTrashleft;
	}

	public void setTagTrashleft(String tagTrashleft) {
		this.tagTrashleft = tagTrashleft;
	}

	public String getTagComment() {
		return this.tagComment;
	}

	public void setTagComment(String tagComment) {
		this.tagComment = tagComment;
	}

	public Set getImages() {
		return this.images;
	}

	public void setImages(Set images) {
		this.images = images;
	}

}
